# render.yaml
services:
  - type: web
    name: laravel-backend
    env: php  # ← Native PHP runtime
    buildCommand: |
      composer install --no-dev
      php artisan optimize:clear
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}